language: node_js

node_js:
    - "8.9"
env:
    - telemetry_local_storage_type=kafka
    - node_env=test

before_script:
    - wget http://archive.apache.org/dist/kafka/0.10.0.0/kafka_2.11-0.10.0.0.tgz -O kafka.tgz
    - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
    - nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
    - nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
    - bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic local.ingestion
    - cd src/
    - npm install

script:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then  npm run test-with-coverage fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run test fi'
